fixed RiC / eoTV & changed tvg-ids for eoTV HD, Bibel TV Impuls, Bibel TV Musik, Radio Bremen TV HD
jnk22/kodinerds-iptv pull request #334
Opened 2020-10-25 23:41 UTC by freddii

2020-10-29 14:57 UTC, freddii reviewed
fixed https://github.com/jnk22/kodinerds-iptv/issues/332

2020-10-29 14:59 UTC, freddii reviewed
fixed https://github.com/jnk22/kodinerds-iptv/issues/318

2020-10-29 15:00 UTC, freddii reviewed
fixed https://github.com/jnk22/kodinerds-iptv/issues/324

2020-10-29 15:02 UTC, freddii reviewed
fixed https://github.com/jnk22/kodinerds-iptv/issues/331

2020-10-29 15:04 UTC, freddii reviewed
fixed https://github.com/jnk22/kodinerds-iptv/issues/287

2020-11-06 19:07 UTC, jnk22 requested changes

2020-11-06 19:07 UTC, jnk22 commented on iptv/clean/clean.m3u
> +https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8
```suggestion
https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8
```

2020-11-06 19:07 UTC, jnk22 commented on iptv/clean/clean_tv_main.m3u
> +https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8
```suggestion
https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8
```

2020-11-06 19:07 UTC, jnk22 commented on iptv/clean/clean_tv.m3u
> +https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8
```suggestion
https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8
```

2020-11-06 19:07 UTC, jnk22 commented on iptv/kodi/kodi_tv_main.m3u
> +https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8
```suggestion
https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8
```

2020-11-06 19:07 UTC, jnk22 commented on iptv/kodi/kodi_tv.m3u
> +https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8
```suggestion
https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8
```

2020-11-06 19:07 UTC, jnk22 commented on iptv/kodi/kodi.m3u
> +https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8
```suggestion
https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8
```

2020-11-06 19:07 UTC, jnk22 commented on iptv/pipe/pipe_tv_main.m3u
> +pipe://ffmpeg -loglevel fatal -i https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8 -vcodec copy -acodec copy -metadata service_name=ARTE\ HD -metadata service_provider=IPTV-DE -mpegts
```suggestion
pipe://ffmpeg -loglevel fatal -i https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8 -vcodec copy -acodec copy -metadata service_name=ARTE\ HD -metadata service_provider=IPTV-DE -mpegts_service_type advanced_codec_digital_hdtv -f mpegts pipe:1
```

2020-11-06 19:07 UTC, jnk22 commented on iptv/pipe/pipe_tv.m3u
> +pipe://ffmpeg -loglevel fatal -i https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8 -vcodec copy -acodec copy -metadata service_name=ARTE\ HD -metadata service_provider=IPTV-DE -mpegts
```suggestion
pipe://ffmpeg -loglevel fatal -i https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8 -vcodec copy -acodec copy -metadata service_name=ARTE\ HD -metadata service_provider=IPTV-DE -mpegts_service_type advanced_codec_digital_hdtv -f mpegts pipe:1
```

2020-11-06 19:07 UTC, jnk22 commented on iptv/pipe/pipe.m3u
> +pipe://ffmpeg -loglevel fatal -i https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8 -vcodec copy -acodec copy -metadata service_name=ARTE\ HD -metadata service_provider=IPTV-DE -mpegts
```suggestion
pipe://ffmpeg -loglevel fatal -i https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8 -vcodec copy -acodec copy -metadata service_name=ARTE\ HD -metadata service_provider=IPTV-DE -mpegts_service_type advanced_codec_digital_hdtv -f mpegts pipe:1
```

2020-11-06 19:13 UTC, jnk22 approved these changes

2020-11-06 19:13 UTC, merged