"Nachrichtensender" Russia Today Deutsch hinzugefügt
jnk22/kodinerds-iptv pull request #509
Opened 2021-12-16 14:10 UTC by forenta

Sendestart 16.12.2021

2021-12-17 00:25 UTC, freddii commented
Pressefreiheit in Russland:
https://www.tagesschau.de/ausland/europa/sacharow-preis-navalny-volkov-101.html

Die Berichterstattung zu Navalny von RT:
https://de.rt.com/tag/Alexei_Nawalny/

RT will einen Fernsehsender für Deutschland:
https://www.tagesschau.de/ausland/europa/russland-fernsehsender-rt-deutschland-101.html

2021-12-17 00:40 UTC, forenta commented
Ich hatte hier nicht die Absicht, für RT zu werben. Wenn wir das Pro & Contra jetzt ausführlich ausdiskutieren, bekommt der Sender meines Erachtens nur unnötige Aufmerksamkeit.
Ab in die FTA-Playlists und gut ist.

2021-12-17 06:26 UTC, bjoerns1983 commented
@freddii Also in der Liste ist bereits Russia Today in mehrfacher Ausführung drin (GB, Spanien, etc.).
Ich habe letztens sogar einen Nord Koreanischen News Sender hinzugefügt.

2021-12-17 09:39 UTC, bjoerns1983 commented
Haha gerade mal ein paar Stunden auf Sendung und schon größere Probleme:
https://www.t-online.de/digital/internet/id_100003966/rt-de-eklat-um-russischen-propagandasender-keine-gueltige-lizenz.html

2021-12-17 09:47 UTC, bjoerns1983 commented
So ich habe das ganze auch nochmal im Forum zur Diskussion gestellt:
https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=665708#post665740

Den PR müsste wir zumindest beim Logo noch mal anpassen.

2021-12-19 11:41 UTC, jnk22 requested changes
Hier würde ich noch folgende Änderungen vorschlagen:
- Name an die sender-eigene Bezeichung angepasst: `RT DE`
- TVG-ID an bisher gängige Bezeichnungen angeglichen: `RT.de`
- Logo von RT-Hauptsender aus diesem Repo verwendet

2021-12-19 11:41 UTC, jnk22 commented on iptv/source.yaml
> +        name: Russia Today Deutsch
```suggestion
        name: RT DE
```

2021-12-19 11:41 UTC, jnk22 commented on iptv/source.yaml
> +        tvg_id: rtdeutsch
```suggestion
        tvg_id: RT.de
```

2021-12-19 11:41 UTC, jnk22 commented on iptv/source.yaml
> +        tvg_name: rtdeutsch
```suggestion
        tvg_name: RT DE
```

2021-12-19 11:41 UTC, jnk22 commented on iptv/source.yaml
> +        tvg_logo: https://i.playboard.app/p/AKedOLR5J2XcArFgkK8OfdX2bT6XeykYPecQYci29AGkpQ/default.jpg
```suggestion
        tvg_logo: https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/rt.png
```

2021-12-19 11:45 UTC, jnk22 commented
@forenta Hier gibt es noch ein Conflict mit deinem Patch, ich glaube da ist was mit den Zeilen von "Bild" durcheinander gekommen.
Kannst du das noch lösen?

Andernfalls können wir da auch einen neuen Merge Request aufmachen.

2021-12-19 13:07 UTC, forenta reviewed
Anpassungen RT-Branding

2021-12-19 13:18 UTC, forenta commented
Lieber einen neuen Request, bevor ich das wieder versemmle.
Bzgl. der Anpassungen gehe ich teilweise mit. Für das deutschsprachige Format wird sowohl auf der Website, als auch im TV-Stream das RT DE-Logo verwendet. Wieso für die kodinerds-M3U dann das Logo des Hauptsenders hier verwenden? Erschwert imho unnötig die Abgrenzung. Bei der Vielzahl an Sendern nutze vermutlich nicht nur ich auf kleinen und mittleren Displays ausschließlich die Logos.
Was den Namen betrifft: Den wechseln ja anscheinend häufiger als Prince in seinen besten Jahren!? Mir erscheint "RT DE" zwar persönlich nicht so glücklich, da, wer keinen Bezug zum Sender hat, damit wohl überhaupt nichts anfangen kann - aber wenn die das so wollen, nur zu. Irgendwer müsste dann nur vllt mal die Liste durchgehen, damit das homogen ist - es sei denn, RT nutzt da selbst keine einheitliche Namensgebung. Derzeit stehen da "RT Spanish HD", "RT HD" mit tvg-id RussiaToday.uk (als englischsprachiger oder russischer Kanal!?).
Ziemliches Durcheinander - da müsste vielleicht mal jemand nach schauen und ein entsprechendes Pull Request erstellen.

2021-12-19 14:36 UTC, jnk22 commented
Ich erstelle dann gleich mal einen neuen Request und schaue mir das mit dem spanischen RT-Sender nochmal genauer an.

2021-12-19 15:34 UTC, jnk22 commented
Ist jetzt als #514 hinzugefügt.

Das Bild habe ich wie von dir angemerkt an das korrekte Bild für 'RT DE' @forenta

2021-12-19 15:34 UTC, closed without merging